const supportedLanguages = [
  { value: "c_cpp", label: "C/C++" },
  { value: "clojure", label: "Clojure" },
  { value: "cobol", label: "Cobol" },
  { value: "csharp", label: "C#" },
  { value: "css", label: "CSS" },
  { value: "dart", label: "Dart" },
  { value: "ejs", label: "EJS" },
  { value: "elixir", label: "Elixir" },
  { value: "elm", label: "Elm" },
  { value: "erlang", label: "Erlang" },
  { value: "fortran", label: "Fortran" },
  { value: "fsharp", label: "F#" },
  { value: "golang", label: "Go" },
  { value: "graphqlschema", label: "GraphQL" },
  { value: "groovy", label: "Groovy" },
  { value: "haml", label: "Haml" },
  { value: "handlebars", label: "Handlebars" },
  { value: "haskell", label: "Haskell" },
  { value: "html", label: "HTML" },
  { value: "jade", label: "Jade" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JavaScript" },
  { value: "json", label: "JSON" },
  { value: "jsp", label: "JSP" },
  { value: "jsx", label: "JSX" },
  { value: "julia", label: "Julia" },
  { value: "kotlin", label: "Kotlin" },
  { value: "less", label: "LESS" },
  { value: "lisp", label: "Lisp" },
  { value: "lua", label: "Lua" },
  { value: "markdown", label: "Markdown" },
  { value: "matlab", label: "MATLAB" },
  { value: "mysql", label: "SQL" },
  { value: "objectivec", label: "Objective C" },
  { value: "pascal", label: "Pascal" },
  { value: "perl", label: "Perl" },
  { value: "php", label: "PHP" },
  { value: "prisma", label: "Prisma" },
  { value: "prolog", label: "Prolog" },
  { value: "python", label: "Python" },
  { value: "r", label: "R Lang" },
  { value: "ruby", label: "Ruby" },
  { value: "rust", label: "Rust" },
  { value: "sass", label: "SCSS/SASS" },
  { value: "scala", label: "Scala" },
  { value: "swift", label: "Swift" },
  { value: "typescript", label: "TypeScript" },
  { value: "xml", label: "XML" },
  { value: "yaml", label: "YAML" },
];
export default supportedLanguages;
